import { Category, Product, Coupon, Order, CustomPrintRequest } from "./types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Desk & Office",
    slug: "desk-and-office",
    description: "Precision-crafted ergonomic cable managers, phone docks, headphone stands, and modular organizers.",
    image: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=800&q=80",
    isActive: true,
    productCount: 4,
  },
  {
    id: "cat-2",
    name: "Home & Decor",
    slug: "home-and-decor",
    description: "Parametric planters, Voronoi lamps, geometric vases, and modern architectural accents.",
    image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
    isActive: true,
    productCount: 4,
  },
  {
    id: "cat-3",
    name: "Gaming & Cosplay",
    slug: "gaming-and-cosplay",
    description: "Custom controller grips, artisan keycaps, cosplay armor pieces, dice towers, and headset mounts.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    isActive: true,
    productCount: 3,
  },
  {
    id: "cat-4",
    name: "Miniatures & Art",
    slug: "miniatures-and-art",
    description: "Ultra-high resolution 8K resin printed tabletop figurines, tabletop terrain, and collector statues.",
    image: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
    isActive: true,
    productCount: 3,
  },
  {
    id: "cat-5",
    name: "Engineering & Parts",
    slug: "engineering-and-parts",
    description: "High-strength functional brackets, robotic gears, replacement automotive clips, and drone chassis.",
    image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
    isActive: true,
    productCount: 3,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "CyberVoronoi Minimalist Table Lamp",
    slug: "cyber-voronoi-table-lamp",
    sku: "PXO-HMD-001",
    shortDescription: "Parametric Voronoi cage lamp casting intricate geometric ambient light patterns.",
    fullDescription: "Engineered with precision computational Voronoi algorithm structures, this ambient lamp is printed using heat-resistant PETG filament. Features an integrated E27/E14 socket fitting and weighted anti-skid base. Perfect for modern workstations and atmospheric bedroom lighting.",
    price: 1899,
    salePrice: 1599,
    costPrice: 650,
    stockQuantity: 18,
    lowStockThreshold: 5,
    material: "PETG Matte Translucent",
    colorOptions: ["Charcoal Black", "Crimson Red", "Bone White", "Cyber Silver"],
    dimensions: "140 x 140 x 220 mm",
    productionTimeDays: 2,
    isFeatured: true,
    isActive: true,
    categoryId: "cat-2",
    rating: 4.9,
    reviewsCount: 32,
    images: [
      {
        id: "img-1",
        url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80",
        altText: "CyberVoronoi Minimalist Table Lamp illuminated",
        sortOrder: 0,
      },
      {
        id: "img-2",
        url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1000&q=80",
        altText: "Lamp detail and layer texture",
        sortOrder: 1,
      },
    ],
  },
  {
    id: "prod-2",
    name: "Vortex Spiral Dual-Device Charging Dock",
    slug: "vortex-spiral-charging-dock",
    sku: "PXO-DSK-002",
    shortDescription: "Weighted dual phone & smartwatch stand with concealed cable routing channel.",
    fullDescription: "Keep your desktop sleek and wire-free. The Vortex Spiral dock houses your smartphone and smartwatch at an optimal 60-degree viewing angle for FaceTime or standby notifications. Crafted with dense 25% gyroid infill for rock-solid stability.",
    price: 1299,
    salePrice: 1099,
    costPrice: 380,
    stockQuantity: 24,
    lowStockThreshold: 6,
    material: "PLA+ High Precision",
    colorOptions: ["Stealth Black", "Titanium Grey", "Vivid Red"],
    dimensions: "115 x 90 x 135 mm",
    productionTimeDays: 1,
    isFeatured: true,
    isActive: true,
    categoryId: "cat-1",
    rating: 4.8,
    reviewsCount: 19,
    images: [
      {
        id: "img-3",
        url: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=1000&q=80",
        altText: "Vortex Spiral Charging Dock on dark wooden desk",
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-3",
    name: "Titan Mechanical Headphone Hanger",
    slug: "titan-mechanical-headphone-hanger",
    sku: "PXO-DSK-003",
    shortDescription: "Under-desk clampable heavy-duty headphone mount with aerospace ribbing.",
    fullDescription: "Built with carbon-fiber reinforced composite PLA, the Titan hanger clamps to desks up to 45mm thick without screws or drilling. The curved cradle matches headband contours to prevent indentation over extended use.",
    price: 849,
    salePrice: null,
    costPrice: 240,
    stockQuantity: 35,
    lowStockThreshold: 10,
    material: "Carbon Fiber Reinforced PLA",
    colorOptions: ["Matte Carbon Black", "Crimson Red Accent"],
    dimensions: "130 x 60 x 110 mm",
    productionTimeDays: 1,
    isFeatured: true,
    isActive: true,
    categoryId: "cat-1",
    rating: 5.0,
    reviewsCount: 47,
    images: [
      {
        id: "img-4",
        url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=80",
        altText: "Titan Mechanical Headphone Hanger mounted",
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-4",
    name: "8K Resin Archmage Wyrm Figurine",
    slug: "8k-resin-archmage-wyrm-figurine",
    sku: "PXO-MIN-004",
    shortDescription: "Ultra-fine tabletop dragon miniature cured at 0.025mm layer thickness.",
    fullDescription: "Printed on our flagship 8K monochrome resin printers, every scale, claw, and horn is captured with microscopic fidelity. Comes washed, cured, and pre-primed with grey acrylic primer ready for hobby painting.",
    price: 1699,
    salePrice: 1449,
    costPrice: 500,
    stockQuantity: 8,
    lowStockThreshold: 4,
    material: "Tough Engineering 8K Resin",
    colorOptions: ["Primed Grey", "Cured Obsidian Black"],
    dimensions: "160 x 130 x 175 mm",
    productionTimeDays: 3,
    isFeatured: true,
    isActive: true,
    categoryId: "cat-4",
    rating: 4.9,
    reviewsCount: 28,
    images: [
      {
        id: "img-5",
        url: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=1000&q=80",
        altText: "8K Resin Archmage Dragon Figurine detail",
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-5",
    name: "Helix Modular Planter with Drainage Reservoir",
    slug: "helix-modular-planter",
    sku: "PXO-HMD-005",
    shortDescription: "Two-piece self-watering succulent pot with concealed drip basin.",
    fullDescription: "A striking geometric statement for your windowsill or coffee table. The inner liner features root-aeration holes while the outer reservoir captures excess water, preventing root rot and water rings on furniture.",
    price: 999,
    salePrice: 799,
    costPrice: 280,
    stockQuantity: 14,
    lowStockThreshold: 5,
    material: "Recycled Matte PLA",
    colorOptions: ["Terracotta", "Stone White", "Matte Charcoal", "Sage Green"],
    dimensions: "120 x 120 x 110 mm",
    productionTimeDays: 2,
    isFeatured: false,
    isActive: true,
    categoryId: "cat-2",
    rating: 4.7,
    reviewsCount: 15,
    images: [
      {
        id: "img-6",
        url: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1000&q=80",
        altText: "Helix Modular Planter with indoor succulent",
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-6",
    name: "Mecha Modular Controller Display Stand",
    slug: "mecha-controller-display-stand",
    sku: "PXO-GAM-006",
    shortDescription: "Gundam-inspired articulated stand compatible with PS5, Xbox & Switch Pro controllers.",
    fullDescription: "Level up your battle station. Features aggressive angular armor panel lines, rubberized contact pads, and an underside compartment for spare thumbsticks and dongles.",
    price: 1149,
    salePrice: null,
    costPrice: 320,
    stockQuantity: 22,
    lowStockThreshold: 6,
    material: "High-Impact ABS",
    colorOptions: ["Mecha White & Red", "Stealth Cyber Black", "Gunmetal Grey"],
    dimensions: "145 x 110 x 165 mm",
    productionTimeDays: 2,
    isFeatured: true,
    isActive: true,
    categoryId: "cat-3",
    rating: 4.9,
    reviewsCount: 39,
    images: [
      {
        id: "img-7",
        url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80",
        altText: "Mecha Controller Stand with wireless gamepad",
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-7",
    name: "Industrial Caliper Wall Dock & Tool Caddy",
    slug: "industrial-caliper-wall-dock",
    sku: "PXO-ENG-007",
    shortDescription: "Workshop wall mount for digital calipers, hex wrenches, and deburring tools.",
    fullDescription: "Designed by makers for makers. Keep your precision measuring instruments safe from drops and scratches. Compatible with French cleat systems or direct wall mounting.",
    price: 699,
    salePrice: 549,
    costPrice: 190,
    stockQuantity: 30,
    lowStockThreshold: 8,
    material: "PETG Industrial Black",
    colorOptions: ["Workshop Orange", "Industrial Black", "High-Vis Red"],
    dimensions: "180 x 75 x 40 mm",
    productionTimeDays: 1,
    isFeatured: false,
    isActive: true,
    categoryId: "cat-5",
    rating: 4.8,
    reviewsCount: 11,
    images: [
      {
        id: "img-8",
        url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80",
        altText: "Industrial tool storage rack",
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-8",
    name: "Foldable Compact Quadcopter Drone Frame (Carbon-PETG)",
    slug: "foldable-quadcopter-drone-frame",
    sku: "PXO-ENG-008",
    shortDescription: "Lightweight 220mm racing drone frame with motor vibration damping.",
    fullDescription: "Engineered for 5-inch props with optimized crash-absorption crumple zones. Printed with 6 wall perimeters in continuous Carbon-Fiber PETG for maximum stiffness and zero prop flutter.",
    price: 2499,
    salePrice: 2199,
    costPrice: 900,
    stockQuantity: 6,
    lowStockThreshold: 3,
    material: "Carbon-Fiber Reinforced PETG",
    colorOptions: ["Matte Carbon Black"],
    dimensions: "220 x 220 x 45 mm",
    productionTimeDays: 3,
    isFeatured: false,
    isActive: true,
    categoryId: "cat-5",
    rating: 5.0,
    reviewsCount: 14,
    images: [
      {
        id: "img-9",
        url: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1000&q=80",
        altText: "Carbon Fiber Drone frame component",
        sortOrder: 0,
      },
    ],
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "c-1",
    code: "WELCOME10",
    type: "PERCENTAGE",
    value: 10,
    minOrderValue: 999,
    maxDiscount: 500,
    usageLimit: 1000,
    timesUsed: 42,
    isActive: true,
  },
  {
    id: "c-2",
    code: "PRINTXO50",
    type: "FIXED_AMOUNT",
    value: 200,
    minOrderValue: 1499,
    maxDiscount: 200,
    usageLimit: 500,
    timesUsed: 18,
    isActive: true,
  },
];

export const SAMPLE_CUSTOM_REQUESTS: CustomPrintRequest[] = [
  {
    id: "cpr-sample-1",
    requestNumber: "CPR-894102-145",
    guestName: "Arjun Mehta",
    guestEmail: "arjun.m@example.com",
    guestPhone: "+91 98451 22345",
    projectTitle: "Custom Ergonomic Split Keyboard Case",
    description: "I need a high-temperature resistant two-piece casing for a Corne v3 split mechanical keyboard with tenting leg stand mounts.",
    intendedUse: "Daily software development workstation hardware",
    quantity: 1,
    dimensions: "160 x 120 x 28 mm (per half)",
    preferredMaterial: "Carbon Fiber PLA",
    preferredColor: "Matte Black",
    finish: "Smooth Vapor & Sanded",
    targetBudget: 3500,
    deadline: "2026-10-15",
    status: "QUOTE_SENT",
    files: [
      {
        id: "f-1",
        filename: "corne_left_top_case.stl",
        fileUrl: "/uploads/corne_left_top_case.stl",
        fileSize: 4821000,
        fileType: "stl",
        estimatedVolumeCm3: 84.5,
        boundingBox: { x: 160, y: 120, z: 28 },
      },
      {
        id: "f-2",
        filename: "corne_right_top_case.stl",
        fileUrl: "/uploads/corne_right_top_case.stl",
        fileSize: 4855000,
        fileType: "stl",
        estimatedVolumeCm3: 85.1,
        boundingBox: { x: 160, y: 120, z: 28 },
      },
    ],
    quote: {
      id: "quote-1",
      requestId: "cpr-sample-1",
      unitPrice: 2800,
      quantity: 1,
      materialCost: 950,
      laborCost: 1650,
      shippingCost: 200,
      totalAmount: 3000,
      productionTimeDays: 4,
      validUntil: "2026-10-05",
      adminMessage: "Hello Arjun! We reviewed your CAD files. We recommend printing in Carbon-Fiber PLA with 5 perimeters and 30% gyroid infill for maximum case rigidity. We can dispatch within 4 business days.",
      status: "PENDING",
    },
    messages: [
      {
        id: "msg-1",
        requestId: "cpr-sample-1",
        senderRole: "CUSTOMER",
        senderName: "Arjun Mehta",
        message: "Hi! Can you please verify if the switch plate tolerancing is 0.15mm?",
        createdAt: "2026-09-18T10:30:00Z",
      },
      {
        id: "msg-2",
        requestId: "cpr-sample-1",
        senderRole: "ADMIN",
        senderName: "PrintXO Studio Lead",
        message: "Yes Arjun! We calibrated our Bambu Lab X1-Carbon for precise 0.12mm switch snap-fit. You will get a crisp click without loose switches.",
        createdAt: "2026-09-18T11:15:00Z",
      },
    ],
    createdAt: "2026-09-17T14:20:00Z",
    updatedAt: "2026-09-18T11:15:00Z",
  },
];
